import type { Metadata } from "next"; // metadata type for the app
import { Inter } from "next/font/google"; // inter font from google fonts
import "./globals.css"; // global css for the app
import { ClerkProvider } from '@clerk/nextjs' // clerk provider for authentication
const inter = Inter({ subsets: ["latin"] }); // inter font with latin subset

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; // metadata for the app
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
